// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.HftInternalService.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LykkeServiceHftInternalServiceModelsV2ApiKeyDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// LykkeServiceHftInternalServiceModelsV2ApiKeyDto class.
        /// </summary>
        public LykkeServiceHftInternalServiceModelsV2ApiKeyDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// LykkeServiceHftInternalServiceModelsV2ApiKeyDto class.
        /// </summary>
        public LykkeServiceHftInternalServiceModelsV2ApiKeyDto(bool enabled, string apiKey = default(string), string walletId = default(string))
        {
            ApiKey = apiKey;
            WalletId = walletId;
            Enabled = enabled;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ApiKey")]
        public string ApiKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "WalletId")]
        public string WalletId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Enabled")]
        public bool Enabled { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
